// Texture images per skin, registered on the map via <Mapbox.Images>. The keys
// are the image ids referenced by fill-pattern/background-pattern in buildSkinStyle.
// Generated by scripts/gen-textures.js.
export const SKIN_TEXTURES: Record<string, Record<string, number>> = {
  minecraft: {
    'mc-grass': require('../../assets/skins/textures/mc-grass.png'),
    'mc-water': require('../../assets/skins/textures/mc-water.png'),
    'mc-dirt': require('../../assets/skins/textures/mc-dirt.png'),
    'mc-stone': require('../../assets/skins/textures/mc-stone.png'),
    'mc-sand': require('../../assets/skins/textures/mc-sand.png'),
  },
  morrowind: {
    parchment: require('../../assets/skins/textures/parchment.png'),
    'parchment-water': require('../../assets/skins/textures/parchment-water.png'),
  },
  skyrim: {
    parchment: require('../../assets/skins/textures/parchment.png'),
    'parchment-water': require('../../assets/skins/textures/parchment-water.png'),
  },
  gta: {},
  pipboy: {},
};

// Which image id fills each map role, per skin (undefined role = keep flat color).
export type SkinPatterns = { bg?: string; water?: string; landuse?: string; building?: string };

export const SKIN_PATTERNS: Record<string, SkinPatterns> = {
  minecraft: { bg: 'mc-grass', water: 'mc-water', landuse: 'mc-dirt', building: 'mc-stone' },
  morrowind: { bg: 'parchment', water: 'parchment-water' },
  skyrim: { bg: 'parchment', water: 'parchment-water' },
};

export function texturesFor(skinId: string): Record<string, number> {
  return SKIN_TEXTURES[skinId] ?? {};
}
export function patternsFor(skinId: string): SkinPatterns {
  return SKIN_PATTERNS[skinId] ?? {};
}
